/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'onTheWay' : null } |
    { 'inProgress' : null },
  'paymentMethod' : { 'mobileMoney' : null } |
    { 'cash' : null },
  'customer' : Principal,
  'storeId' : StoreId,
  'tableNumber' : [] | [bigint],
  'specialNote' : [] | [string],
  'items' : Array<[ProductId, bigint]>,
}
export interface Product {
  'id' : ProductId,
  'marketplace' : boolean,
  'stockQty' : bigint,
  'storeId' : StoreId,
  'name' : string,
  'outOfStock' : boolean,
  'imageRef' : ExternalBlob,
  'discount' : [] | [bigint],
  'price' : bigint,
}
export type ProductId = string;
export interface Review {
  'customer' : Principal,
  'storeId' : StoreId,
  'text' : [] | [string],
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface Store {
  'id' : StoreId,
  'mobileMoneyNumber' : string,
  'owner' : Principal,
  'isBlocked' : boolean,
  'name' : string,
  'category' : string,
  'location' : string,
}
export type StoreId = string;
export type TermsType = { 'storeOwnerTerms' : null } |
  { 'customerTerms' : null };
export interface UserProfile {
  'acceptedStoreOwnerTerms' : boolean,
  'dateOfBirth' : string,
  'role' : UserRole,
  'stateOfResidence' : string,
  'fullName' : string,
  'nationality' : string,
  'email' : string,
  'isSuspended' : boolean,
  'acceptedCustomerTerms' : boolean,
  'phoneNumber' : string,
}
export type UserRole = { 'customer' : null } |
  { 'storeOwner' : null } |
  { 'superAdmin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTerms' : ActorMethod<[{ 'termsType' : TermsType }], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'blockStore' : ActorMethod<[StoreId], undefined>,
  'bootstrapSuperAdmin' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<
    [StoreId, string, ExternalBlob, bigint, bigint],
    ProductId
  >,
  'createStore' : ActorMethod<[string, string, string, string], StoreId>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Principal>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllStores' : ActorMethod<[], Array<Store>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMarketplaceProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyStores' : ActorMethod<[], Array<Store>>,
  'getStore' : ActorMethod<[StoreId], [] | [Store]>,
  'getStoreOrders' : ActorMethod<[StoreId], Array<Order>>,
  'getStoreProducts' : ActorMethod<[StoreId], Array<Product>>,
  'getStoreReviews' : ActorMethod<[StoreId], Array<Review>>,
  'getTermsContent' : ActorMethod<[TermsType], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAcceptedTerms' : ActorMethod<[{ 'termsType' : TermsType }], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [
      StoreId,
      Array<[ProductId, bigint]>,
      [] | [bigint],
      [] | [string],
      { 'mobileMoney' : null } |
        { 'cash' : null },
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTermsContent' : ActorMethod<[TermsType, string], undefined>,
  'submitReview' : ActorMethod<[StoreId, bigint, [] | [string]], undefined>,
  'suspendCustomer' : ActorMethod<[Principal], undefined>,
  'unblockStore' : ActorMethod<[StoreId], undefined>,
  'unsuspendCustomer' : ActorMethod<[Principal], undefined>,
  'updateOrderStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'onTheWay' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, ExternalBlob, bigint, bigint, [] | [bigint], boolean],
    undefined
  >,
  'updateStore' : ActorMethod<
    [StoreId, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];