/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TermsType = IDL.Variant({
  'storeOwnerTerms' : IDL.Null,
  'privacyPolicy' : IDL.Null,
  'customerTerms' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StoreId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductId = IDL.Text;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'onTheWay' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'paymentMethod' : IDL.Variant({
    'mobileMoney' : IDL.Null,
    'cash' : IDL.Null,
  }),
  'customer' : IDL.Principal,
  'storeId' : StoreId,
  'tableNumber' : IDL.Opt(IDL.Nat),
  'specialNote' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
});
export const Store = IDL.Record({
  'id' : StoreId,
  'mobileMoneyNumber' : IDL.Text,
  'owner' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'customer' : IDL.Null,
  'storeOwner' : IDL.Null,
  'superAdmin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'acceptedStoreOwnerTerms' : IDL.Bool,
  'dateOfBirth' : IDL.Text,
  'role' : UserRole,
  'stateOfResidence' : IDL.Text,
  'fullName' : IDL.Text,
  'nationality' : IDL.Text,
  'email' : IDL.Text,
  'isSuspended' : IDL.Bool,
  'acceptedCustomerTerms' : IDL.Bool,
  'phoneNumber' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'marketplace' : IDL.Bool,
  'stockQty' : IDL.Nat,
  'storeId' : StoreId,
  'name' : IDL.Text,
  'outOfStock' : IDL.Bool,
  'imageRef' : ExternalBlob,
  'discount' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
});
export const Review = IDL.Record({
  'customer' : IDL.Principal,
  'storeId' : StoreId,
  'text' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Nat,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTerms' : IDL.Func([IDL.Record({ 'termsType' : TermsType })], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'blockStore' : IDL.Func([StoreId], [], []),
  'bootstrapSuperAdmin' : IDL.Func([], [], []),
  'createProduct' : IDL.Func(
      [StoreId, IDL.Text, ExternalBlob, IDL.Nat, IDL.Nat],
      [ProductId],
      [],
    ),
  'createStore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StoreId],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMarketplaceProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getStore' : IDL.Func([StoreId], [IDL.Opt(Store)], ['query']),
  'getStoreOrders' : IDL.Func([StoreId], [IDL.Vec(Order)], ['query']),
  'getStoreProducts' : IDL.Func([StoreId], [IDL.Vec(Product)], ['query']),
  'getStoreReviews' : IDL.Func([StoreId], [IDL.Vec(Review)], ['query']),
  'getTermsContent' : IDL.Func([TermsType], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAcceptedTerms' : IDL.Func(
      [IDL.Record({ 'termsType' : TermsType })],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        StoreId,
        IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Variant({ 'mobileMoney' : IDL.Null, 'cash' : IDL.Null }),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTermsContent' : IDL.Func([TermsType, IDL.Text], [], []),
  'submitReview' : IDL.Func([StoreId, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'suspendCustomer' : IDL.Func([IDL.Principal], [], []),
  'unblockStore' : IDL.Func([StoreId], [], []),
  'unsuspendCustomer' : IDL.Func([IDL.Principal], [], []),
  'updateOrderStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'onTheWay' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateStore' : IDL.Func(
      [StoreId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TermsType = IDL.Variant({
    'storeOwnerTerms' : IDL.Null,
    'privacyPolicy' : IDL.Null,
    'customerTerms' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StoreId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductId = IDL.Text;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'onTheWay' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'paymentMethod' : IDL.Variant({
      'mobileMoney' : IDL.Null,
      'cash' : IDL.Null,
    }),
    'customer' : IDL.Principal,
    'storeId' : StoreId,
    'tableNumber' : IDL.Opt(IDL.Nat),
    'specialNote' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
  });
  const Store = IDL.Record({
    'id' : StoreId,
    'mobileMoneyNumber' : IDL.Text,
    'owner' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'customer' : IDL.Null,
    'storeOwner' : IDL.Null,
    'superAdmin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'acceptedStoreOwnerTerms' : IDL.Bool,
    'dateOfBirth' : IDL.Text,
    'role' : UserRole,
    'stateOfResidence' : IDL.Text,
    'fullName' : IDL.Text,
    'nationality' : IDL.Text,
    'email' : IDL.Text,
    'isSuspended' : IDL.Bool,
    'acceptedCustomerTerms' : IDL.Bool,
    'phoneNumber' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'marketplace' : IDL.Bool,
    'stockQty' : IDL.Nat,
    'storeId' : StoreId,
    'name' : IDL.Text,
    'outOfStock' : IDL.Bool,
    'imageRef' : ExternalBlob,
    'discount' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
  });
  const Review = IDL.Record({
    'customer' : IDL.Principal,
    'storeId' : StoreId,
    'text' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTerms' : IDL.Func([IDL.Record({ 'termsType' : TermsType })], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'blockStore' : IDL.Func([StoreId], [], []),
    'bootstrapSuperAdmin' : IDL.Func([], [], []),
    'createProduct' : IDL.Func(
        [StoreId, IDL.Text, ExternalBlob, IDL.Nat, IDL.Nat],
        [ProductId],
        [],
      ),
    'createStore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StoreId],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMarketplaceProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getStore' : IDL.Func([StoreId], [IDL.Opt(Store)], ['query']),
    'getStoreOrders' : IDL.Func([StoreId], [IDL.Vec(Order)], ['query']),
    'getStoreProducts' : IDL.Func([StoreId], [IDL.Vec(Product)], ['query']),
    'getStoreReviews' : IDL.Func([StoreId], [IDL.Vec(Review)], ['query']),
    'getTermsContent' : IDL.Func([TermsType], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAcceptedTerms' : IDL.Func(
        [IDL.Record({ 'termsType' : TermsType })],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          StoreId,
          IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Variant({ 'mobileMoney' : IDL.Null, 'cash' : IDL.Null }),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTermsContent' : IDL.Func([TermsType, IDL.Text], [], []),
    'submitReview' : IDL.Func([StoreId, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'suspendCustomer' : IDL.Func([IDL.Principal], [], []),
    'unblockStore' : IDL.Func([StoreId], [], []),
    'unsuspendCustomer' : IDL.Func([IDL.Principal], [], []),
    'updateOrderStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'onTheWay' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateStore' : IDL.Func(
        [StoreId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };