/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: ProductId;
    marketplace: boolean;
    stockQty: bigint;
    storeId: StoreId;
    name: string;
    outOfStock: boolean;
    imageRef: ExternalBlob;
    discount?: bigint;
    price: bigint;
}
export interface UserProfile {
    acceptedStoreOwnerTerms: boolean;
    dateOfBirth: string;
    role: UserRole;
    stateOfResidence: string;
    fullName: string;
    nationality: string;
    email: string;
    isSuspended: boolean;
    acceptedCustomerTerms: boolean;
    phoneNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: bigint;
    status: Variant_pending_completed_onTheWay_inProgress;
    paymentMethod: Variant_mobileMoney_cash;
    customer: Principal;
    storeId: StoreId;
    tableNumber?: bigint;
    specialNote?: string;
    items: Array<[ProductId, bigint]>;
}
export type StoreId = string;
export type ProductId = string;
export interface Store {
    id: StoreId;
    mobileMoneyNumber: string;
    owner: Principal;
    isBlocked: boolean;
    name: string;
    category: string;
    location: string;
}
export interface Review {
    customer: Principal;
    storeId: StoreId;
    text?: string;
    timestamp: bigint;
    rating: bigint;
}
export enum TermsType {
    storeOwnerTerms = "storeOwnerTerms",
    customerTerms = "customerTerms"
}
export enum UserRole {
    customer = "customer",
    storeOwner = "storeOwner",
    superAdmin = "superAdmin"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_mobileMoney_cash {
    mobileMoney = "mobileMoney",
    cash = "cash"
}
export enum Variant_pending_completed_onTheWay_inProgress {
    pending = "pending",
    completed = "completed",
    onTheWay = "onTheWay",
    inProgress = "inProgress"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptTerms(arg0: {
        termsType: TermsType;
    }): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    blockStore(storeId: StoreId): Promise<void>;
    bootstrapSuperAdmin(): Promise<void>;
    createProduct(storeId: StoreId, name: string, imageRef: ExternalBlob, price: bigint, stockQty: bigint): Promise<ProductId>;
    createStore(name: string, category: string, location: string, mobileMoneyNumber: string): Promise<StoreId>;
    deleteProduct(id: ProductId): Promise<void>;
    getAllCustomers(): Promise<Array<Principal>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllStores(): Promise<Array<Store>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getMarketplaceProducts(): Promise<Array<Product>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyStores(): Promise<Array<Store>>;
    getStore(id: StoreId): Promise<Store | null>;
    getStoreOrders(storeId: StoreId): Promise<Array<Order>>;
    getStoreProducts(storeId: StoreId): Promise<Array<Product>>;
    getStoreReviews(storeId: StoreId): Promise<Array<Review>>;
    getTermsContent(termsType: TermsType): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasAcceptedTerms(arg0: {
        termsType: TermsType;
    }): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(storeId: StoreId, items: Array<[ProductId, bigint]>, tableNumber: bigint | null, specialNote: string | null, paymentMethod: Variant_mobileMoney_cash): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveTermsContent(termsType: TermsType, content: string): Promise<void>;
    submitReview(storeId: StoreId, rating: bigint, text: string | null): Promise<void>;
    suspendCustomer(customer: Principal): Promise<void>;
    unblockStore(storeId: StoreId): Promise<void>;
    unsuspendCustomer(customer: Principal): Promise<void>;
    updateOrderStatus(orderId: bigint, status: Variant_pending_completed_onTheWay_inProgress): Promise<void>;
    updateProduct(id: ProductId, name: string, imageRef: ExternalBlob, price: bigint, stockQty: bigint, discount: bigint | null, marketplace: boolean): Promise<void>;
    updateStore(id: StoreId, name: string, category: string, location: string, mobileMoneyNumber: string): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Order as _Order, Product as _Product, ProductId as _ProductId, Review as _Review, Store as _Store, StoreId as _StoreId, TermsType as _TermsType, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptTerms(arg0: {
        termsType: TermsType;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTerms(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTerms(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockStore(arg0: StoreId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockStore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockStore(arg0);
            return result;
        }
    }
    async bootstrapSuperAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapSuperAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapSuperAdmin();
            return result;
        }
    }
    async createProduct(arg0: StoreId, arg1: string, arg2: ExternalBlob, arg3: bigint, arg4: bigint): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createStore(arg0: string, arg1: string, arg2: string, arg3: string): Promise<StoreId> {
        if (this.processError) {
            try {
                const result = await this.actor.createStore(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStore(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStores(): Promise<Array<Store>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStores();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketplaceProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceProducts();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceProducts();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStores(): Promise<Array<Store>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStores();
            return result;
        }
    }
    async getStore(arg0: StoreId): Promise<Store | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStore(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStore(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreOrders(arg0: StoreId): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreOrders(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreOrders(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreProducts(arg0: StoreId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreProducts(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreProducts(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreReviews(arg0: StoreId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreReviews(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreReviews(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTermsContent(arg0: TermsType): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTermsContent(to_candid_TermsType_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTermsContent(to_candid_TermsType_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAcceptedTerms(arg0: {
        termsType: TermsType;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAcceptedTerms(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAcceptedTerms(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: StoreId, arg1: Array<[ProductId, bigint]>, arg2: bigint | null, arg3: string | null, arg4: Variant_mobileMoney_cash): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n37(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg3), to_candid_variant_n37(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveTermsContent(arg0: TermsType, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTermsContent(to_candid_TermsType_n9(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTermsContent(to_candid_TermsType_n9(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async submitReview(arg0: StoreId, arg1: bigint, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async suspendCustomer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendCustomer(arg0);
            return result;
        }
    }
    async unblockStore(arg0: StoreId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockStore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockStore(arg0);
            return result;
        }
    }
    async unsuspendCustomer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendCustomer(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: Variant_pending_completed_onTheWay_inProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_variant_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_variant_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: string, arg2: ExternalBlob, arg3: bigint, arg4: bigint, arg5: bigint | null, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateStore(arg0: StoreId, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStore(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStore(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Order_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Store]): Store | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        onTheWay: null;
    } | {
        inProgress: null;
    };
    paymentMethod: {
        mobileMoney: null;
    } | {
        cash: null;
    };
    customer: Principal;
    storeId: _StoreId;
    tableNumber: [] | [bigint];
    specialNote: [] | [string];
    items: Array<[_ProductId, bigint]>;
}): {
    id: bigint;
    status: Variant_pending_completed_onTheWay_inProgress;
    paymentMethod: Variant_mobileMoney_cash;
    customer: Principal;
    storeId: StoreId;
    tableNumber?: bigint;
    specialNote?: string;
    items: Array<[ProductId, bigint]>;
} {
    return {
        id: value.id,
        status: from_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_variant_n18(_uploadFile, _downloadFile, value.paymentMethod),
        customer: value.customer,
        storeId: value.storeId,
        tableNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tableNumber)),
        specialNote: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.specialNote)),
        items: value.items
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    acceptedStoreOwnerTerms: boolean;
    dateOfBirth: string;
    role: _UserRole;
    stateOfResidence: string;
    fullName: string;
    nationality: string;
    email: string;
    isSuspended: boolean;
    acceptedCustomerTerms: boolean;
    phoneNumber: string;
}): {
    acceptedStoreOwnerTerms: boolean;
    dateOfBirth: string;
    role: UserRole;
    stateOfResidence: string;
    fullName: string;
    nationality: string;
    email: string;
    isSuspended: boolean;
    acceptedCustomerTerms: boolean;
    phoneNumber: string;
} {
    return {
        acceptedStoreOwnerTerms: value.acceptedStoreOwnerTerms,
        dateOfBirth: value.dateOfBirth,
        role: from_candid_UserRole_n23(_uploadFile, _downloadFile, value.role),
        stateOfResidence: value.stateOfResidence,
        fullName: value.fullName,
        nationality: value.nationality,
        email: value.email,
        isSuspended: value.isSuspended,
        acceptedCustomerTerms: value.acceptedCustomerTerms,
        phoneNumber: value.phoneNumber
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    marketplace: boolean;
    stockQty: bigint;
    storeId: _StoreId;
    name: string;
    outOfStock: boolean;
    imageRef: _ExternalBlob;
    discount: [] | [bigint];
    price: bigint;
}): Promise<{
    id: ProductId;
    marketplace: boolean;
    stockQty: bigint;
    storeId: StoreId;
    name: string;
    outOfStock: boolean;
    imageRef: ExternalBlob;
    discount?: bigint;
    price: bigint;
}> {
    return {
        id: value.id,
        marketplace: value.marketplace,
        stockQty: value.stockQty,
        storeId: value.storeId,
        name: value.name,
        outOfStock: value.outOfStock,
        imageRef: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.imageRef),
        discount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.discount)),
        price: value.price
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: Principal;
    storeId: _StoreId;
    text: [] | [string];
    timestamp: bigint;
    rating: bigint;
}): {
    customer: Principal;
    storeId: StoreId;
    text?: string;
    timestamp: bigint;
    rating: bigint;
} {
    return {
        customer: value.customer,
        storeId: value.storeId,
        text: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.text)),
        timestamp: value.timestamp,
        rating: value.rating
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    onTheWay: null;
} | {
    inProgress: null;
}): Variant_pending_completed_onTheWay_inProgress {
    return "pending" in value ? Variant_pending_completed_onTheWay_inProgress.pending : "completed" in value ? Variant_pending_completed_onTheWay_inProgress.completed : "onTheWay" in value ? Variant_pending_completed_onTheWay_inProgress.onTheWay : "inProgress" in value ? Variant_pending_completed_onTheWay_inProgress.inProgress : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mobileMoney: null;
} | {
    cash: null;
}): Variant_mobileMoney_cash {
    return "mobileMoney" in value ? Variant_mobileMoney_cash.mobileMoney : "cash" in value ? Variant_mobileMoney_cash.cash : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    storeOwner: null;
} | {
    superAdmin: null;
}): UserRole {
    return "customer" in value ? UserRole.customer : "storeOwner" in value ? UserRole.storeOwner : "superAdmin" in value ? UserRole.superAdmin : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n33(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TermsType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TermsType): _TermsType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    acceptedStoreOwnerTerms: boolean;
    dateOfBirth: string;
    role: UserRole;
    stateOfResidence: string;
    fullName: string;
    nationality: string;
    email: string;
    isSuspended: boolean;
    acceptedCustomerTerms: boolean;
    phoneNumber: string;
}): {
    acceptedStoreOwnerTerms: boolean;
    dateOfBirth: string;
    role: _UserRole;
    stateOfResidence: string;
    fullName: string;
    nationality: string;
    email: string;
    isSuspended: boolean;
    acceptedCustomerTerms: boolean;
    phoneNumber: string;
} {
    return {
        acceptedStoreOwnerTerms: value.acceptedStoreOwnerTerms,
        dateOfBirth: value.dateOfBirth,
        role: to_candid_UserRole_n40(_uploadFile, _downloadFile, value.role),
        stateOfResidence: value.stateOfResidence,
        fullName: value.fullName,
        nationality: value.nationality,
        email: value.email,
        isSuspended: value.isSuspended,
        acceptedCustomerTerms: value.acceptedCustomerTerms,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    termsType: TermsType;
}): {
    termsType: _TermsType;
} {
    return {
        termsType: to_candid_TermsType_n9(_uploadFile, _downloadFile, value.termsType)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TermsType): {
    storeOwnerTerms: null;
} | {
    customerTerms: null;
} {
    return value == TermsType.storeOwnerTerms ? {
        storeOwnerTerms: null
    } : value == TermsType.customerTerms ? {
        customerTerms: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_mobileMoney_cash): {
    mobileMoney: null;
} | {
    cash: null;
} {
    return value == Variant_mobileMoney_cash.mobileMoney ? {
        mobileMoney: null
    } : value == Variant_mobileMoney_cash.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    customer: null;
} | {
    storeOwner: null;
} | {
    superAdmin: null;
} {
    return value == UserRole.customer ? {
        customer: null
    } : value == UserRole.storeOwner ? {
        storeOwner: null
    } : value == UserRole.superAdmin ? {
        superAdmin: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_onTheWay_inProgress): {
    pending: null;
} | {
    completed: null;
} | {
    onTheWay: null;
} | {
    inProgress: null;
} {
    return value == Variant_pending_completed_onTheWay_inProgress.pending ? {
        pending: null
    } : value == Variant_pending_completed_onTheWay_inProgress.completed ? {
        completed: null
    } : value == Variant_pending_completed_onTheWay_inProgress.onTheWay ? {
        onTheWay: null
    } : value == Variant_pending_completed_onTheWay_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
